#!/bin/sh

set -e

PACKAGE_NAME=$1
SCHEMA_NAME=$2
OUTPUT_DIR=$3
PACKAGE_BUILD_DIR=${4:-"."}

OUTPUT_PATH="${OUTPUT_DIR}/${PACKAGE_NAME}.framework"

IPHONEOS_FRAMEWORK_DIR="${PACKAGE_BUILD_DIR}/Release-iphoneos/${SCHEMA_NAME}/${PACKAGE_NAME}.framework"
SIMULATOR_FRAMEWORK_DIR="${PACKAGE_BUILD_DIR}/Release-iphonesimulator/${SCHEMA_NAME}/${PACKAGE_NAME}.framework"
if [ -d $IPHONEOS_FRAMEWORK_DIR ]; then
  mkdir -p "${OUTPUT_PATH}"
  cp -a $IPHONEOS_FRAMEWORK_DIR/ "${OUTPUT_PATH}"
else
  echo "No frameworks at ${IPHONEOS_FRAMEWORK_DIR}"
  exit 1
fi

xcrun lipo -create \
-output \
"${OUTPUT_PATH}/${PACKAGE_NAME}" \
$IPHONEOS_FRAMEWORK_DIR/$PACKAGE_NAME \
$SIMULATOR_FRAMEWORK_DIR/$PACKAGE_NAME

SWIFTMODULE_PATH="${SIMULATOR_FRAMEWORK_DIR}/Modules/${PACKAGE_NAME}.swiftmodule/"
if [ -d $SWIFTMODULE_PATH ]; then
  cp -r "${SWIFTMODULE_PATH}" "${OUTPUT_PATH}/Modules/${PACKAGE_NAME}.swiftmodule"
fi

